// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8OOFdv8YHWJhyXkM8ByanIXLhbYbwD6A',
    appId: '1:427245998849:web:b9e8759707dd3ba03c8100',
    messagingSenderId: '427245998849',
    projectId: 'reddit-clone-12e0b',
    authDomain: 'reddit-clone-12e0b.firebaseapp.com',
    storageBucket: 'reddit-clone-12e0b.appspot.com',
    measurementId: 'G-KCQHM4WJV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgYGdtaI-njR5YMsrBZJQQF48hEr-b_0',
    appId: '1:427245998849:android:c07bbb0db7fc4df53c8100',
    messagingSenderId: '427245998849',
    projectId: 'reddit-clone-12e0b',
    storageBucket: 'reddit-clone-12e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0D3m43TbPwDWUbgEGZD_6ZNLFc_CrBc',
    appId: '1:427245998849:ios:14b776faa71f07db3c8100',
    messagingSenderId: '427245998849',
    projectId: 'reddit-clone-12e0b',
    storageBucket: 'reddit-clone-12e0b.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0D3m43TbPwDWUbgEGZD_6ZNLFc_CrBc',
    appId: '1:427245998849:ios:1770faa1527e97cf3c8100',
    messagingSenderId: '427245998849',
    projectId: 'reddit-clone-12e0b',
    storageBucket: 'reddit-clone-12e0b.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
